name: Zip Link Updater

on:
  release:
    types: [published]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Get Tag
        id: get_tag
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: return context.payload.release.tag_name;

      - name: Checkout Main Branch
        uses: actions/checkout@v2.0.0
        with:
          ref: main
      - name: Update Zip URL
        uses: actions/github-script@0.3.0
        id: update_zip
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            console.log(require("process").cwd());
            const fs = require("fs");
            let pkg = JSON.parse(fs.readFileSync("repository.json", {encoding: "utf8"}));
            pkg.packages[0].link = context.payload.release.zipball_url;
            fs.writeFileSync("repository.json", JSON.stringify(pkg, null, 2));

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update .zip URL to version ${{ steps.get_tag.outputs.result }}" repository.json
          git push "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
